version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: academy_db
      MYSQL_USER: academy
      MYSQL_PASSWORD: securepassword
      TZ: Europe/Paris
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-prootpassword"]
      interval: 3s
      timeout: 5s
      retries: 10

  backend:
    build: .
    environment:
      DB_HOST: mysql
      DB_USER: academy
      DB_PASSWORD: securepassword
      DB_NAME: academy_db
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  mysql_data:
